
version: "3.9"

services:
  web:
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - .:/app
      command: pm2 start npm --name "AppName" -- start
      ports:
        - "8000:8000"
      restart: always
      depends_on:
        - db
