version: "3.9"

services:
  web:
      build:
        context: .
        dockerfile: Dockerfile
      # volumes:
      #   - .:/app
      command: pm2 serve dist/ 8000 --name 'horlakz' --spa --no-daemon
      ports:
        - "8001:8000"
      restart: unless-stopped
