
version: "3.9"

services:
  web:
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - .:/app
      command: pm2 serve dist/ 8001 --name 'horlakz' --spa --no-daemon
      ports:
        - "8001:8001"
