name: Deploy to Linode

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker images
        run: |
          docker build . -t horlakz:${{ github.sha }}

  run:
    runs-on: self-hosted

    needs: build

    steps:
      - name: remove previous running images
        run: docker rm --force horlakz

      - name: Run Docker images
        run: |
          docker run -d -p 3400:5000 --name horlakz horlakz:${{ github.sha }}
